## Sztuczne sieci neuronowe - laboratorium 1

### NumPy - powtórzenie
Podstawową strukturą w NumPy jest tablica wielowymiarowa: n-dimensional array (ndarray):
- przechowuje elementy określonego typu
- typowo elementy zajmują sąsiednie bloki w pamięci

Dzięki temu jest ona szybsza niż standardowa lista w Pythonie i pozwala na tzw. wektoryzację obliczeń.

https://raw.githubusercontent.com/enthought/Numpy-Tutorial-SciPyConf-2020/master/slides.pdf

In [1]:
import numpy as np

#### Ćwiczenie

Niech `a = np.array([0, 1, 2, 3])`.

Jaki będzie rezultat poniższych wywołań?
- `type(a)`
- `a.dtype`
- `a.shape`
- `a.ndim`

In [2]:
a = np.array([0, 1, 2, 3])
print(type(a))
print(a.dtype)
print(a.shape)
print(a.ndim)

<class 'numpy.ndarray'>
int32
(4,)
1


### Ćwiczenie

Niech `a = np.array([1, 2, 3, 4])` i `b = np.array([2, 3, 4, 5])`.

Jaki będzie rezultat poniższych wywołań?

- `a + b`
- `a * b`
- `a ** b`

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
print(a + b)
print(a * b)
print(a ** b)

[3 5 7 9]
[ 2  6 12 20]
[   1    8   81 1024]


### Ćwiczenie 

Niech `a = np.array([[0, 1, 2, 3], [10, 11, 12, 13]])`

Jaki będzie rezultat poniższych wywołań?
- `a.shape`
- `a.size`
- `a.ndim`
- `a[1]`

In [4]:
a = np.array([[0, 1, 2, 3], [10, 11, 12, 13]])
print(a.shape)
print(a.size)
print(a.ndim)
print(a[1])

(2, 4)
8
2
[10 11 12 13]


### Ćwiczenie 

Niech `a = np.array([10,11,12,13,14])`

Jaki będzie rezultat poniższych wywołań?
- `a[1:3]`
- `a[1:-2]`
- `a[:3]`
- `a[-2:]`
- `a[::2]`

In [ ]:
a = np.array([10,11,12,13,14])

print(a[1:3])
print(a[1:-2])
print(a[:3])
print(a[-2:])
print(a[::2])

### Ćwiczenie

Niech `a = np.array([0, 1, 2, 3, 4])`.
Jaka (i dlaczego) będzie zawartość `a` po wywołaniu kolejno:
- `b = a[2:4]`
- `b[0] = 10` ?

In [5]:
a = np.array([0, 1, 2, 3, 4])
b = a[2:4]
print(b[0])

2


### Ćwiczenie

Jaka będzie zawartość `b` po wywołaniu kolejno:
- `a = np.arange(0, 80, 10)`
- `mask = np.array([0, 1, 1, 0, 0, 1, 0, 0], dtype=bool)`
- `b = a[mask]` ?


In [6]:
a = np.arange(0, 80, 10)
mask = np.array([0, 1, 1, 0, 0, 1, 0, 0], dtype=bool)
b = a[mask]
print(b)

[10 20 50]


### Ćwiczenie

Niech `a = np.array([[1, 2, 3], [4, 5, 6]])`

Jaki będzie rezultat poniższych wywołań:
- `a.sum()`
- `a.sum(axis=0)`
- `a.sum(axis=-1)`
- `np.max(a, axis=1)`
- `np.argmax(a, axis=1)`
- `np.mean(a, axis=0)`

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=-1))
print(np.max(a, axis=1))
print(np.argmax(a, axis=1))
print(np.mean(a, axis=0))

21
[5 7 9]
[ 6 15]
[3 6]
[2 2]
[2.5 3.5 4.5]


### Ćwiczenie

Jaka (i dlaczego) będzie zawartość zmiennej `b` po wywołaniu kolejno poniższych komend?

- `a = np.arange(-2, 2) ** 2`
- `mask = a % 2 == 0`
- `b = np.where(mask)`

In [8]:
a = np.arange(-2, 2) ** 2
mask = a % 2 == 0
b = np.where(mask)
print(b)

(array([0, 2], dtype=int64),)


### Ćwiczenie

Niech `a = np.array([1, 0, 0, 1])` i `b = np.array([1, 2, 3, 4])`

Jaki będzie rezultat wywołania `np.dot(a, b)`?

In [9]:
a = np.array([1, 0, 0, 1])
b = np.array([1, 2, 3, 4])

print(np.dot(a, b)) # iloczyn skalarny

5


### Ćwiczenie

Niech `a = np.array([[1, 0], [0, 1]])` i `b = np.array([[1, 2], [3, 4]])`

Jaki będzie rezultat wywołania `np.dot(a, b)`?

In [10]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[1, 2], [3, 4]])

print(np.dot(a, b))

[[1 2]
 [3 4]]


### Ćwiczenie
Niech `a = np.array([[1, 2, 3], [4, 5, 6]])`.

Jaki będzie rezultat wywołania `np.transpose(a)` (lub `a.T`)?

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

### PyTorch - podstawy
https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [1]:
import torch

W PyTorch podstawową strukturą, analogiczną do `np.array` jest tensor (`torch.Tensor`). Można go zaincjalizować na kilka sposobów, np.:

1) z listy list
```
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
```

2) z np.array
```
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# w drugą stronę: x_np.numpy() pozwala na konwersję Tensora do numpy
# uwaga: np array oraz tensor współdzielą pamięć i zmiany w jednym obiekcie spowodują zmiany w drugim
```

3) z użyciem wbudowanych funkcji (np. rand, zeros, ones)

```
shape = (2, 3,)
rand_tensor = torch.rand(shape)
```

Tensor posiada takie atrybuty, jak:
- shape - krotka (tuple) opisująca jego wymiary
- dtype - przechowyway typ danych
- device - domyślnie `cpu`

Jeśli posiadamy kartę graficzną, możemy sprawdzić, czy jest "wykryta" przez PyTorch: `torch.cuda.is_available()`.
Jeśli tak, możemy dla przyspieszenia obliczeń przenieść tensor na GPU: `tensor = tensor.to('cuda')`

### Ćwiczenie

Stwórz tensor rozmiaru `(3, 2)` zainicjalizowany liczbami losowymi. Sprawdź typ stworzonego obiektu, typ przechowywanych danych oraz atrybuty `shape` i `device`. Jeśli posiadasz kartę graficzną obsługującą CUDA, spróbuj przenieść na nią stworzony tensor.

In [5]:
shape = (3, 2)
tensor = torch.rand(shape)
print(type(tensor))
print(tensor.type())
print(tensor.shape)
print(tensor.device)
if torch.cuda.is_available():
    print("is GPU")
    tensor = tensor.to('cuda')
    print(tensor.device)
else:
    print("no GPU")


<class 'torch.Tensor'>
torch.FloatTensor
torch.Size([3, 2])
cpu
is GPU
cuda:0


### Ćwiczenie
Niech `points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])`

Wypróbuj, korzystając z tego tensora, jak dla tensorów działa indeksowanie i slicing.

Co zwróci `points[0, 1]`? Na wyniku tej operacji wykonaj metodę `.item()`.

In [9]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points[0,1].item())
print(points[0 : 1])

1.0
tensor([[4., 1.]])


### Ćwiczenie

`torch.cat` i `torch.stack` to funkcje pozwalające łączyć ze sobą tensory. Spróbuj zaobserwować różnicę pomiędzy tymi funkcjami korzystając z kodu poniżej.

In [11]:
t = torch.ones((4, 2))

t1 = torch.cat([t, t, t], dim=0)
t2 = torch.stack([t, t, t], dim=0)
print(t1.shape)
print(t2.shape)

torch.Size([12, 2])
torch.Size([3, 4, 2])
